### PR TITLE
Remove unused IronControlState import.

### PR DESCRIPTION
**Pull request by bicknellr**

### CODE REVIEW

**Comment by bicknellr** [comment]
Hmm, this goes a little deeper. Some things (like PaperInkyFocusBehavior) expect iron-button-state to import iron-control-state.

**Comment by notwaldorf** [comment]
`IronButtonState` is defining one of those abstract methods `IronControlState` is calling (https://github.com/PolymerElements/iron-behaviors/blob/master/iron-button-state.html#L204) which is why that dependency is listed

**Comment by bicknellr** [comment]
Maybe `IronButtonState` include `IronControlState` in its list of behaviors?

**Comment by notwaldorf** [comment]
Agreed, but won't this add a duplicate 'IronControlState` to all the elements that have already been importing both of them?

**Pull request closed without merging**
